name: Publish ADR-Py

on:
  workflow_run:
    workflows: [Test ADR-Py]
    types: [completed]

permissions:
  contents: write

jobs:
  publish:
    description: Build and publish package on tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          enable-cache: true
          activate-environment: true

      - name: Install project dependencies
        run: make sync-deps

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.TEST_PYPI_TOKEN }} --publish-url https://test.pypi.org/legacy/

#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: dist/*
